# Default Template for Invoice Reader 2.0
---
key:
  pattern: "Default"

inv_date:
  pattern: 'Ký\s*ngày\D*((0[1-9]|[12][0-9]|3[01])[- /.](0[1-9]|1[012])[- /.](19|20)\d\d)'
  flag: IGNORECASE

inv_form:
  pattern: 'Mẫu\s*số.*\:(.*)'

inv_serial:
  pattern: 'Ký\s*hiệu.*\:(.*)'

inv_number:
  pattern: 'Số.*\:(\d*)'

inv_description:
  pattern:

seller_name:
  pattern:
  flag: IGNORECASE

seller_tax_code:
  pattern:

buyer_name:
  pattern:

buyer_tax_code:
  pattern:

amount_before_tax:
  pattern:

amount_tax:
  pattern:

amount_after_tax:
  pattern:

tax_rate:
  pattern:
